language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - ./gradlew test jacocoTestReport coveralls
